import type { Staff, Student, Class, Book, BookLoan, Activity, DashboardStats } from '@/types';

export const mockStaff: Staff[] = [
  {
    id: '1',
    email: 'superadmin@pxpmanagement.es',
    firstName: 'Super',
    lastName: 'Admin',
    role: 'superadmin',
    position: 'System Administrator',
    department: 'Management',
    phone: '+34 600 000 001',
    status: 'active',
    dateJoined: '2023-01-15',
    createdAt: '2023-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    email: 'admin@pxpmanagement.es',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    position: 'Administrator',
    department: 'Management',
    phone: '+34 600 000 002',
    status: 'active',
    dateJoined: '2023-02-01',
    createdAt: '2023-02-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    email: 'maria.garcia@pxpmanagement.es',
    firstName: 'Maria',
    lastName: 'Garcia',
    role: 'teacher',
    position: 'Senior Teacher',
    department: 'Education',
    phone: '+34 600 000 003',
    status: 'active',
    dateJoined: '2023-03-10',
    dateOfBirth: '1985-05-15',
    gender: 'female',
    bio: 'Experienced language teacher with 10+ years in adult education.',
    createdAt: '2023-03-10',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    email: 'john.smith@pxpmanagement.es',
    firstName: 'John',
    lastName: 'Smith',
    role: 'librarian',
    position: 'Head Librarian',
    department: 'Library',
    phone: '+34 600 000 004',
    status: 'active',
    dateJoined: '2023-04-05',
    dateOfBirth: '1978-11-22',
    gender: 'male',
    bio: 'Passionate about literacy and community learning.',
    createdAt: '2023-04-05',
    updatedAt: '2024-01-15',
  },
  {
    id: '5',
    email: 'anna.martinez@pxpmanagement.es',
    firstName: 'Anna',
    lastName: 'Martinez',
    role: 'teacher',
    position: 'Teacher',
    department: 'Education',
    phone: '+34 600 000 005',
    status: 'active',
    dateJoined: '2023-06-15',
    dateOfBirth: '1990-03-08',
    gender: 'female',
    createdAt: '2023-06-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '6',
    email: 'carlos.lopez@pxpmanagement.es',
    firstName: 'Carlos',
    lastName: 'Lopez',
    role: 'teacher',
    position: 'Teacher',
    department: 'Education',
    phone: '+34 600 000 006',
    status: 'inactive',
    dateJoined: '2023-08-01',
    dateOfBirth: '1988-07-20',
    gender: 'male',
    createdAt: '2023-08-01',
    updatedAt: '2024-01-15',
  },
];

export const mockStudents: Student[] = [
  {
    id: '1',
    firstName: 'Ahmed',
    lastName: 'Hassan',
    email: 'ahmed.hassan@email.com',
    phone: '+34 611 111 111',
    gradeLevel: 'Beginner',
    enrollmentDate: '2024-01-10',
    status: 'active',
    parentName: 'Fatima Hassan',
    parentPhone: '+34 611 111 112',
    emergencyName: 'Omar Hassan',
    emergencyPhone: '+34 611 111 113',
    emergencyRelationship: 'Brother',
    classes: ['1', '2'],
    attendanceRate: 92,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    firstName: 'Maria',
    lastName: 'Rodriguez',
    email: 'maria.r@email.com',
    phone: '+34 622 222 222',
    gradeLevel: 'Intermediate',
    enrollmentDate: '2023-09-05',
    status: 'active',
    parentName: 'Jose Rodriguez',
    parentPhone: '+34 622 222 223',
    emergencyName: 'Ana Rodriguez',
    emergencyPhone: '+34 622 222 224',
    emergencyRelationship: 'Sister',
    classes: ['2'],
    attendanceRate: 88,
    createdAt: '2023-09-05',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    firstName: 'Yusuf',
    lastName: 'Khan',
    email: 'yusuf.khan@email.com',
    phone: '+34 633 333 333',
    gradeLevel: 'Advanced',
    enrollmentDate: '2023-06-20',
    status: 'active',
    emergencyName: 'Amina Khan',
    emergencyPhone: '+34 633 333 334',
    emergencyRelationship: 'Mother',
    classes: ['3'],
    attendanceRate: 95,
    createdAt: '2023-06-20',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    firstName: 'Sofia',
    lastName: 'Andersson',
    email: 'sofia.a@email.com',
    phone: '+34 644 444 444',
    gradeLevel: 'Beginner',
    enrollmentDate: '2024-01-05',
    status: 'active',
    emergencyName: 'Lars Andersson',
    emergencyPhone: '+34 644 444 445',
    emergencyRelationship: 'Father',
    classes: ['1'],
    attendanceRate: 85,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-15',
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Chen',
    email: 'david.chen@email.com',
    phone: '+34 655 555 555',
    gradeLevel: 'Intermediate',
    enrollmentDate: '2023-11-15',
    status: 'inactive',
    emergencyName: 'Li Chen',
    emergencyPhone: '+34 655 555 556',
    emergencyRelationship: 'Mother',
    classes: [],
    attendanceRate: 60,
    createdAt: '2023-11-15',
    updatedAt: '2024-01-15',
  },
];

export const mockClasses: Class[] = [
  {
    id: '1',
    name: 'Català Bàsic A1',
    description: 'Curs de català per a principiants. Aprendràs les bases de la gramàtica i vocabulari essencial.',
    teacherId: '3',
    teacherName: 'Maria Garcia',
    schedule: [
      { day: 'monday', startTime: '09:00', endTime: '11:00' },
      { day: 'wednesday', startTime: '09:00', endTime: '11:00' },
    ],
    room: 'Aula 101',
    maxCapacity: 20,
    status: 'active',
    createdAt: '2023-09-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Català Intermedi B1',
    description: 'Millora el teu català amb conversa i gramàtica avançada.',
    teacherId: '5',
    teacherName: 'Anna Martinez',
    schedule: [
      { day: 'tuesday', startTime: '10:00', endTime: '12:00' },
      { day: 'thursday', startTime: '10:00', endTime: '12:00' },
    ],
    room: 'Aula 102',
    maxCapacity: 15,
    status: 'active',
    createdAt: '2023-09-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    name: 'Català Avançat C1',
    description: 'Perfecciona el teu català amb literatura i expressió oral.',
    teacherId: '3',
    teacherName: 'Maria Garcia',
    schedule: [
      { day: 'friday', startTime: '14:00', endTime: '16:00' },
    ],
    room: 'Aula 103',
    maxCapacity: 12,
    status: 'active',
    createdAt: '2023-09-01',
    updatedAt: '2024-01-15',
  },
];

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Gramàtica Catalana per a Principiants',
    author: 'Maria Pilar',
    isbn: '978-84-12345-01-1',
    publisher: 'Edicions Catalanes',
    category: 'Language Learning',
    description: 'Guia completa de gramàtica catalana per a estudiants de nivell A1-A2.',
    totalCopies: 10,
    availableCopies: 7,
    location: 'Shelf A1',
    condition: 'good',
    status: 'available',
    createdAt: '2023-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Conversa Catalana Diària',
    author: 'Joan Martí',
    isbn: '978-84-12345-02-8',
    publisher: 'Llengua Viva',
    category: 'Language Learning',
    description: 'Exercicis de conversa per a la vida quotidiana.',
    totalCopies: 8,
    availableCopies: 5,
    location: 'Shelf A1',
    condition: 'good',
    status: 'available',
    createdAt: '2023-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '3',
    title: 'Història de Barcelona',
    author: 'Anna Soler',
    isbn: '978-84-12345-03-5',
    publisher: 'Història Local',
    category: 'History',
    description: 'Descobreix la història de la ciutat de Barcelona.',
    totalCopies: 5,
    availableCopies: 0,
    location: 'Shelf B2',
    condition: 'good',
    status: 'borrowed',
    createdAt: '2023-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '4',
    title: 'Cultura Catalana Contemporània',
    author: 'Pere Roca',
    isbn: '978-84-12345-04-2',
    publisher: 'Cultura Edicions',
    category: 'Culture',
    description: 'Una visió de la cultura catalana actual.',
    totalCopies: 6,
    availableCopies: 6,
    location: 'Shelf C1',
    condition: 'good',
    status: 'available',
    createdAt: '2023-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '5',
    title: 'Diccionari Català-Anglès',
    author: 'Equip Editorial',
    isbn: '978-84-12345-05-9',
    publisher: 'Diccionaris Plus',
    category: 'Reference',
    description: 'Diccionari bilingüe català-anglès amb 50,000 entrades.',
    totalCopies: 3,
    availableCopies: 2,
    location: 'Shelf R1',
    condition: 'good',
    status: 'available',
    createdAt: '2023-01-01',
    updatedAt: '2024-01-15',
  },
];

export const mockBookLoans: BookLoan[] = [
  {
    id: '1',
    bookId: '3',
    bookTitle: 'Història de Barcelona',
    borrowerId: '1',
    borrowerName: 'Ahmed Hassan',
    borrowerType: 'student',
    lendingDate: '2024-01-01',
    dueDate: '2024-01-15',
    status: 'active',
  },
  {
    id: '2',
    bookId: '3',
    bookTitle: 'Història de Barcelona',
    borrowerId: '2',
    borrowerName: 'Maria Rodriguez',
    borrowerType: 'student',
    lendingDate: '2024-01-05',
    dueDate: '2024-01-19',
    status: 'active',
  },
  {
    id: '3',
    bookId: '3',
    bookTitle: 'Història de Barcelona',
    borrowerId: '3',
    borrowerName: 'Yusuf Khan',
    borrowerType: 'student',
    lendingDate: '2024-01-08',
    dueDate: '2024-01-22',
    status: 'active',
  },
  {
    id: '4',
    bookId: '5',
    bookTitle: 'Diccionari Català-Anglès',
    borrowerId: '4',
    borrowerName: 'Sofia Andersson',
    borrowerType: 'student',
    lendingDate: '2024-01-10',
    dueDate: '2024-01-24',
    status: 'active',
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'student_added',
    description: 'New student enrolled',
    userId: '2',
    userName: 'Admin User',
    targetId: '1',
    targetName: 'Ahmed Hassan',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    type: 'book_borrowed',
    description: 'Book borrowed by student',
    userId: '4',
    userName: 'John Smith',
    targetId: '3',
    targetName: 'Història de Barcelona',
    createdAt: '2024-01-10T14:30:00Z',
  },
  {
    id: '3',
    type: 'class_created',
    description: 'New class created',
    userId: '3',
    userName: 'Maria Garcia',
    targetId: '1',
    targetName: 'Català Bàsic A1',
    createdAt: '2024-01-08T09:00:00Z',
  },
  {
    id: '4',
    type: 'staff_added',
    description: 'New staff member added',
    userId: '1',
    userName: 'Super Admin',
    targetId: '5',
    targetName: 'Anna Martinez',
    createdAt: '2024-01-05T11:00:00Z',
  },
  {
    id: '5',
    type: 'book_returned',
    description: 'Book returned by student',
    userId: '4',
    userName: 'John Smith',
    targetId: '2',
    targetName: 'Conversa Catalana Diària',
    createdAt: '2024-01-12T16:00:00Z',
  },
];

export function getDashboardStats(): DashboardStats {
  const activeStaff = mockStaff.filter(s => s.status === 'active').length;
  const activeStudents = mockStudents.filter(s => s.status === 'active').length;
  const availableBooks = mockBooks.reduce((sum, b) => sum + b.availableCopies, 0);
  const borrowedBooks = mockBooks.reduce((sum, b) => sum + (b.totalCopies - b.availableCopies), 0);
  
  return {
    totalStaff: mockStaff.length,
    activeStaff,
    inactiveStaff: mockStaff.length - activeStaff,
    totalStudents: mockStudents.length,
    activeStudents,
    inactiveStudents: mockStudents.length - activeStudents,
    totalClasses: mockClasses.length,
    totalBooks: mockBooks.reduce((sum, b) => sum + b.totalCopies, 0),
    availableBooks,
    borrowedBooks,
    overdueBooks: 0,
  };
}
